# HERE AND NOW AI - AI is Good
spring.application.name=mcp-server
server.port=8081
spring.ai.mcp.server.name=pdf-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
spring.mvc.async.request-timeout=300000
