# HERE AND NOW AI - AI is Good
spring.application.name=mcp-client
spring.ai.ollama.chat.model=gpt-oss:20b
spring.ai.mcp.client.sse.connections.pdf-server.url=http://localhost:8081
spring.main.web-application-type=none
spring.ai.mcp.client.request-timeout=120s
spring.ai.ollama.init.timeout=120s
